apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: people-service
  labels:
    app: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-service
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
      - name: people-service
        image: allokubs/people-rest-service:1.0
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:   
            secretKeyRef:
               name: mysql-pass
               key: password
        ports:
        - containerPort: 80
          name: people-service
#      imagePullSecrets:
#       - name: ocirsecret     
---
#People Service           
apiVersion: v1
kind: Service
metadata:
  name: people-service
  labels:
    app: people-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: people-service